name:                haskell-energy-metrics-simulator
version:             0.1.0.0
github:              "daniel-crodrigues/haskell-energy-metrics-simulator"
license:             BSD-3-Clause
author:              "Daniel Rodigues"
maintainer:          "example@example.com"
copyright:           "2023 Daniel Rodrigues"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on GitHub at <https://github.com/daniel-crodrigues/haskell-energy-metrics-simulator#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cassava
- vector
- directory
- time
- random
- text
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-energy-metrics-simulator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - network-uri
    - net-mqtt
    - haskell-energy-metrics-simulator
    - connection
    - bytestring
    - text

tests:
  haskell-energy-metrics-simulator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-energy-metrics-simulator
    - hspec  
